matrix:
  include:
    - language: python
      sudo: yes
      dist: xenial
      python:
        - "3.7"
      env:
        - CMPUT404_POSTGRES_HOST
        - CMPUT404_POSTGRES_PORT
        - CMPUT404_POSTGRES_NAME
        - CMPUT404_POSTGRES_USER
        - CMPUT404_POSTGRES_PASSWORD
      install:
        - pip install -r requirements.txt
      script:
        - export TEST_POSTGRES_NAME=${TRAVIS_COMMIT::8}
        - python manage.py test --noinput
        - pylint api && pylint hyperion
    - language: node_js
      node_js:
        - "10"
      cache: yarn
      before_install:
        - cd client
      install:
        - yarn install
      script:
        - yarn test
notifications:
  email:
    on_success: never
    on_failure: always
