# Generated by Django 2.1.5 on 2019-01-30 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hyperion', '0002_auto_20190130_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hyperion.Server'),
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together={('name',)},
        ),
    ]
