# Generated by Django 2.1.5 on 2019-02-05 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hyperion', '0002_auto_20190201_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibleTo',
            field=models.ManyToManyField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to='hyperion.UserProfile'), related_name='visible', to='hyperion.UserProfile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to='hyperion.UserProfile'),
        ),
    ]
