# Generated by Django 2.1.5 on 2019-02-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyperion', '0002_auto_20190201_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
