# Generated by Django 2.1.5 on 2019-02-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyperion', '0003_userprofile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github',
            field=models.URLField(blank=True),
        ),
    ]
