# Generated by Django 2.1.7 on 2019-03-01 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyperion', '0011_auto_20190301_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='post',
            name='source',
        ),
    ]
