# Generated by Django 2.1.7 on 2019-03-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("hyperion", "0012_auto_20190301_2034")]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="create_date", new_name="published"
        )
    ]
