# Generated by Django 2.1.7 on 2019-03-24 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hyperion', '0013_auto_20190312_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='server',
            name='accept',
        ),
        migrations.RemoveField(
            model_name='server',
            name='name',
        ),
        migrations.RemoveField(
            model_name='server',
            name='password',
        ),
    ]
