# Generated by Django 2.1.7 on 2019-03-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("hyperion", "0015_auto_20190324_0228")]

    operations = [
        migrations.AddField(
            model_name="server", name="endpoint", field=models.CharField(blank=True, max_length=200)
        )
    ]
