# Generated by Django 2.1.7 on 2019-03-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("hyperion", "0016_server_endpoint")]

    operations = [
        migrations.AddField(
            model_name="server", name="url", field=models.CharField(blank=True, max_length=200)
        )
    ]
