# Generated by Django 2.1.7 on 2019-03-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("hyperion", "0017_server_url")]

    operations = [
        migrations.AddField(
            model_name="server",
            name="required_trailing_slash",
            field=models.BooleanField(default=False),
        )
    ]
