# Generated by Django 2.1.7 on 2019-04-02 05:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyperion', '0020_auto_20190401_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visible_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None),
        ),
    ]
